# Generated by Django 6.0.1 on 2026-03-26 11:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True)),
                ('purpose', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='visitor_photos/')),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('host', models.ForeignKey(help_text='The staff member they are visiting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
