# Generated by Django 6.0.1 on 2026-03-29 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visitlog',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Direct', 'Direct Entry')], default='Direct', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitlog',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors', to=settings.AUTH_USER_MODEL),
        ),
    ]
