# Generated by Django 6.0.1 on 2026-02-27 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_remove_center_created_at_center_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('Day', 'Day'), ('Night', 'Night')], max_length=10)),
                ('image', models.FileField(blank=True, null=True, upload_to='attendance_sheets/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.center')),
            ],
            options={
                'unique_together': {('center', 'date', 'shift')},
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('Worker', 'Worker'), ('Female', 'Female'), ('Operator', 'Operator'), ('Supervisor', 'Supervisor')], max_length=50)),
                ('is_company_staff', models.BooleanField(default=False, help_text='True if direct employee, False if contractor')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manpower.contractor')),
            ],
            options={
                'unique_together': {('name', 'contractor')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_scanned_name', models.CharField(blank=True, max_length=150)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='manpower.attendancesheet')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manpower.person')),
            ],
        ),
    ]
