# Generated by Django 6.0.1 on 2026-02-27 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_center_created_at_center_category_and_more'),
        ('manpower', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='person',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manpower_people', to='inventory.center'),
        ),
        migrations.AddField(
            model_name='person',
            name='shift_preference',
            field=models.CharField(choices=[('Day', 'Day'), ('Night', 'Night'), ('Both', 'Both')], default='Both', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('name', 'contractor', 'center')},
        ),
    ]
