# Generated by Django 6.0.1 on 2026-02-28 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_center_created_at_center_category_and_more'),
        ('manpower', '0002_alter_person_unique_together_person_center_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceentry',
            name='sheet',
        ),
        migrations.AddField(
            model_name='attendanceentry',
            name='shift',
            field=models.CharField(choices=[('Day', 'Day'), ('Night', 'Night')], default='day', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='is_company_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('file', models.FileField(blank=True, null=True, upload_to='daily_rosters/%Y/%m/')),
                ('day_production_kgs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('night_production_kgs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.center')),
            ],
            options={
                'unique_together': {('center', 'date')},
            },
        ),
        migrations.AddField(
            model_name='attendanceentry',
            name='record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='manpower.dailyrecord'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AttendanceSheet',
        ),
    ]
