# Generated by Django 5.2.10 on 2026-01-26 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Standardized lowercase name', max_length=200, unique=True)),
                ('category', models.CharField(help_text='Official reporting category', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_name', models.CharField(max_length=200, unique=True)),
                ('master_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='inventory.masteritem')),
            ],
        ),
        migrations.CreateModel(
            name='StockSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='stock_sheets/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.center')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('center', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_category', models.CharField(max_length=100)),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('raw_name_scanned', models.CharField(blank=True, max_length=200)),
                ('master_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.masteritem')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='inventory.stocksheet')),
            ],
        ),
    ]
