# Generated by Django 6.0.1 on 2026-01-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocksheet',
            name='image',
            field=models.FileField(upload_to='stock_sheets/%Y/%m/'),
        ),
    ]
