# Generated by Django 6.0.1 on 2026-02-24 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_stocksheet_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemalias',
            options={'verbose_name_plural': 'Item Aliases'},
        ),
        migrations.AlterModelOptions(
            name='stockentry',
            options={'verbose_name_plural': 'Stock Entries'},
        ),
        migrations.AlterField(
            model_name='stocksheet',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.CreateModel(
            name='WhatsAppReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.center')),
            ],
            options={
                'unique_together': {('center', 'date')},
            },
        ),
    ]
