# Generated by Django 6.0.1 on 2026-02-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_itemalias_options_alter_stockentry_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='created_at',
        ),
        migrations.AddField(
            model_name='center',
            name='category',
            field=models.CharField(blank=True, choices=[('HD', 'HD'), ('LD', 'LD')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='center',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
