# Generated by Django 6.0.1 on 2026-03-10 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_center_created_at_center_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterMasterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_items', to='inventory.center')),
            ],
        ),
        migrations.CreateModel(
            name='CenterItemAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_name', models.CharField(max_length=255)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.center')),
                ('mapped_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.centermasteritem')),
            ],
        ),
    ]
