# Generated by Django 6.0.1 on 2026-03-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_printtemplate_printtemplateitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksheet',
            name='copied_from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksheet',
            name='is_carried_over',
            field=models.BooleanField(default=False),
        ),
    ]
