# Generated by Django 6.0.1 on 2026-03-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_stocksheet_copied_from_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printtemplate',
            name='source_centers',
            field=models.ManyToManyField(blank=True, to='inventory.center'),
        ),
    ]
