# Generated by Django 6.0.1 on 2026-03-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_centerclassification_center_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='dispatch',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='inward',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='production',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='closing_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
