# Generated by Django 6.0.3 on 2026-04-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_stockentry_dispatch_stockentry_inward_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('columns_config', models.JSONField(default=list, help_text='Array of column objects defining labels, sources, and filters.')),
                ('static_rows_config', models.JSONField(blank=True, default=list, help_text='Array defining target inputs or mathematical formulas.')),
                ('data_config', models.JSONField(default=dict, help_text='Defines the core data pull (e.g., source model, grouping axis).')),
            ],
        ),
    ]
