# Generated by Django 6.0.3 on 2026-04-21 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_reporttemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetReportColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=200)),
                ('monthly_target', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('selected_items', models.JSONField(default=list)),
                ('display_order', models.IntegerField(default=0)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.center')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='TargetReportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Monthly Purchase Main', max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ReportTemplate',
        ),
        migrations.AddField(
            model_name='targetreportcolumn',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='inventory.targetreportconfig'),
        ),
    ]
