# Generated by Django 6.0.3 on 2026-04-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_targetreportcolumn_targetreportconfig_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetreportcolumn',
            name='center',
        ),
        migrations.AddField(
            model_name='targetreportcolumn',
            name='centers',
            field=models.ManyToManyField(related_name='target_columns', to='inventory.center'),
        ),
    ]
