# Generated by Django 5.2.10 on 2026-05-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_centeruploadtoken_and_stocksheet_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksheet',
            name='review_image',
            field=models.FileField(blank=True, null=True, upload_to='stock_sheets/reviews/%Y/%m/'),
        ),
    ]
