# Generated by Django 5.2.10 on 2026-06-11 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_notification_case4_replaced'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterPairingCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=12)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairing_codes', to='inventory.center')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupervisorDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('fcm_token', models.TextField(blank=True, default='')),
                ('push_subscription', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('paired_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_devices', to='inventory.center')),
            ],
            options={
                'ordering': ['-paired_at'],
            },
        ),
        migrations.AddField(
            model_name='centerpairingcode',
            name='used_by_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.supervisordevice'),
        ),
    ]
