# Generated by Django 5.2.10 on 2026-06-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_supervisor_pwa_device_pairing'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorReminderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('start_time', models.TimeField(help_text='First reminder of the day (Asia/Kolkata)')),
                ('interval_hours', models.PositiveSmallIntegerField(default=2)),
                ('deadline_time', models.TimeField(help_text='Stop reminding after this time each day')),
                ('lookback_days', models.PositiveSmallIntegerField(default=7, help_text='How many past days to check for missing sheets')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Supervisor reminder settings',
                'verbose_name_plural': 'Supervisor reminder settings',
            },
        ),
        migrations.AddField(
            model_name='supervisordevice',
            name='last_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supervisordevice',
            name='label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
