# Generated by Django 6.0.3 on 2026-03-24 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('AC_MACHINERY', 'AC & Machinery'), ('PARTS', 'Machinery Parts'), ('RENTALS', 'Factory Rentals'), ('FIRE_SAFETY', 'Fire Extinguisher'), ('LABOUR_SAFETY', 'Labour Safety')], max_length=50)),
                ('purchase_or_start_date', models.DateField()),
                ('next_due_date', models.DateField()),
                ('specific_details', models.JSONField(blank=True, default=dict)),
                ('enable_reminders', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_date', models.DateField()),
                ('new_due_date', models.DateField()),
                ('document_image', models.ImageField(blank=True, null=True, upload_to='maintenance_docs/')),
                ('remarks', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='maintenance.asset')),
            ],
        ),
    ]
