# Generated by Django 6.0.3 on 2026-03-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('AC', 'AC'), ('MACHINERY', 'Machinery'), ('RENTALS', 'Factory Rentals'), ('FIRE_SAFETY', 'Fire Extinguisher'), ('LABOUR_SAFETY', 'Labour Safety')], max_length=50),
        ),
    ]
