# Generated by Django 6.0.3 on 2026-03-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_asset_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
