# Generated by Django 6.0.3 on 2026-03-25 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_add_maintenance_frequency'),
        ('maintenance', '0003_asset_location'),
    ]

    operations = [
    ]
