# Generated by Django 6.0.3 on 2026-03-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_merge_20260325_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('AC', 'AC'), ('MACHINERY', 'Machinery'), ('RENTALS', 'Factory Rentals'), ('FIRE_SAFETY', 'Fire Extinguisher')], max_length=50),
        ),
    ]
