# Generated by Django 6.0.3 on 2026-03-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='machine_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='anchor_type',
            field=models.CharField(choices=[('DATE_ONLY', 'Daily Report (One per Day)'), ('DATE_MACHINE', 'Machine Report (One per Machine per Day)')], default='DATE_ONLY', max_length=20),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='document_type',
            field=models.CharField(choices=[('PRINT_ONLY', 'View & Print Only (Static SOPs)'), ('DIGITAL_ENTRY', 'Digital Entry (Filled on Website)'), ('PHYSICAL_OCR', 'Physical OCR (Scanned & Extracted)')], default='PHYSICAL_OCR', max_length=20),
        ),
        migrations.AddField(
            model_name='reportversion',
            name='update_reason',
            field=models.CharField(blank=True, help_text='Reason for update (e.g., Added rows, Fixed typo)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='ai_prompt_schema',
            field=models.JSONField(blank=True, help_text='JSON schema (Not required for Print Only)', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together={('template', 'report_date', 'shift', 'machine_id')},
        ),
    ]
