# Generated by Django 6.0.3 on 2026-03-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_dailyreport_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttemplate',
            name='anchor_type',
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='custom_categories',
            field=models.JSONField(blank=True, help_text='Array of custom parameters', null=True),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('HALF_YEARLY', 'Half-Yearly'), ('YEARLY', 'Yearly (Financial Year)')], default='DAILY', max_length=20),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='tracking_type',
            field=models.CharField(choices=[('TIME_ONLY', 'Time-Based Only'), ('TIME_AND_CUSTOM', 'Time + Custom Category (e.g., Machines, Shifts)')], default='TIME_ONLY', max_length=20),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='ai_prompt_schema',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='html_layout',
            field=models.TextField(help_text='HTML table structure'),
        ),
    ]
