# Generated by Django 6.0.3 on 2026-03-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_remove_documenttemplate_anchor_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='custom_extraction_prompt',
            field=models.TextField(blank=True, help_text='AI instructions for OCR', null=True),
        ),
    ]
