# Generated by Django 6.0.3 on 2026-03-30 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_documenttemplate_custom_extraction_prompt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='l1_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='l1_signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='l1_signed_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='l2_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='l2_signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='l2_signed_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft / In Progress'), ('PENDING_L2', 'Pending L2 Approval'), ('LOCKED', 'Approved & Locked')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='l1_signature_role',
            field=models.CharField(blank=True, choices=[('PREPARED', 'Prepared By'), ('TESTED', 'Tested By'), ('CHECKED', 'Checked By'), ('CALIBRATED', 'Calibrated By')], help_text='The Maker role', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='l2_signature_role',
            field=models.CharField(blank=True, choices=[('APPROVED', 'Approved By'), ('VERIFIED', 'Verified By')], help_text='The Checker role', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reportversion',
            name='action_type',
            field=models.CharField(choices=[('NEW_UPLOAD', 'New Scan Upload'), ('MANUAL_EDIT', 'Manual Correction'), ('L1_SIGNATURE', 'L1 (Maker) Signature Applied'), ('L2_SIGNATURE', 'L2 (Checker) Signature Applied'), ('REJECTED', 'Rejected / Returned to Draft')], max_length=20),
        ),
    ]
