# Generated by Django 6.0.3 on 2026-03-25 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0010_stockentry_dispatch_stockentry_inward_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(help_text='e.g., can_merge_masters', max_length=100)),
                ('display_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NexusApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('icon_class', models.CharField(blank=True, help_text='FontAwesome class e.g., fa-solid fa-box', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('allowed_features', models.ManyToManyField(blank=True, related_name='roles', to='hub.appfeature')),
                ('allowed_apps', models.ManyToManyField(related_name='roles', to='hub.nexusapp')),
            ],
        ),
        migrations.AddField(
            model_name='appfeature',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='hub.nexusapp'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_centers', models.ManyToManyField(blank=True, related_name='authorized_users', to='inventory.center')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='hub.customrole')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nexus_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='appfeature',
            unique_together={('app', 'code_name')},
        ),
    ]
