# Generated by Django 6.0.3 on 2026-03-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
        ('records', '0003_remove_documenttemplate_anchor_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='allowed_centers',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allowed_apps',
            field=models.ManyToManyField(blank=True, to='hub.nexusapp'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allowed_sites',
            field=models.ManyToManyField(blank=True, related_name='authorized_users', to='records.site'),
        ),
    ]
