# Generated by Django 6.0.3 on 2026-03-28 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_remove_userprofile_role_userprofile_roles'),
        ('records', '0004_documenttemplate_custom_extraction_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allowed_departments',
            field=models.ManyToManyField(blank=True, related_name='authorized_signers', to='records.department'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='primary_app',
            field=models.ForeignKey(blank=True, help_text="Null means 'All / System Wide'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_users', to='hub.nexusapp'),
        ),
    ]
